version = 1

test_patterns = ["**/*.spec.ts", "**/*.test.ts", "**/*_test.py", "**/*_tests.py", "**/test_*.py"]

exclude_patterns = [
  ".archive/**",
  "classic/**",
  "**/node_modules/**",
  "**/__pycache__/**",
  "**/.next/**",
  "**/dist/**",
  "**/build/**",
  "**/*.min.js",
  "**/coverage/**"
]

[[analyzers]]
name = "javascript"

[analyzers.meta]
plugins = ["react"]
environment = ["nodejs"]
dialect = "typescript"

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.10.x"
